# https://github.com/bitnami/charts/tree/main/bitnami/mongodb
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongocluster-bitnami
  namespace: widebot-mongo-ns
spec:
  releaseName: mongo
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "13.16.0"
  interval: 1m
  values:
